// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  _Cryptocurrency_ = ""Cryptocurrency"",
  Corner_Stone_Brick_Wall = "Corner Stone Brick Wall",
  Corner_Stone_Brick_Wall_2 = "Corner Stone Brick Wall_2",
  Corner_Stone_Brick_Wall_2_3 = "Corner Stone Brick Wall_2_3",
  Corner_Stone_Brick_Wall_2_4 = "Corner Stone Brick Wall_2_4",
  Fliptop_Bin = "Fliptop Bin",
  Flower_01 = "Flower 01",
  Flower_01_2 = "Flower 01_2",
  Flower_Pot_01 = "Flower Pot 01",
  Flower_Pot_01_2 = "Flower Pot 01_2",
  Food_Box___Empty = "Food Box - Empty",
  Golden_Plate = "Golden Plate",
  Golden_Plate_2 = "Golden Plate_2",
  Grass_Sprout = "Grass Sprout",
  Grass_Sprout_2 = "Grass Sprout_2",
  Grass_Sprout_3 = "Grass Sprout_3",
  Grass_Sprout_4 = "Grass Sprout_4",
  Grass_Sprout_4_5 = "Grass Sprout_4_5",
  Grass_Sprout_6 = "Grass Sprout_6",
  Grass_Sprout_6_7 = "Grass Sprout_6_7",
  Grass_Sprout_6_8 = "Grass Sprout_6_8",
  Ground = "Ground",
  Lit_Candle = "Lit Candle",
  Lit_Candle_2 = "Lit Candle_2",
  Rabbit_Ear_Grass = "Rabbit-Ear Grass",
  Road_Cobble_Angled = "Road Cobble Angled",
  Road_Cobble_Angled_2 = "Road Cobble Angled_2",
  Road_Cobble_Angled_2_3 = "Road Cobble Angled_2_3",
  Road_Cobble_Angled_3 = "Road Cobble Angled_3",
  Road_Cobble_Straight = "Road Cobble Straight",
  Road_Cobble_Straight_2 = "Road Cobble Straight_2",
  Road_Cobble_Straight_2_3 = "Road Cobble Straight_2_3",
  Road_Cobble_Straight_2_3_4 = "Road Cobble Straight_2_3_4",
  Road_Cobble_Straight_2_4 = "Road Cobble Straight_2_4",
  Road_Cobble_Straight_2_5 = "Road Cobble Straight_2_5",
  Road_Cobble_Straight_3 = "Road Cobble Straight_3",
  Road_Cobble_Straight_3_4 = "Road Cobble Straight_3_4",
  Road_Cobble_Straight_3_4_5 = "Road Cobble Straight_3_4_5",
  Road_Cobble_Straight_3_5 = "Road Cobble Straight_3_5",
  Road_Cobble_Straight_3_6 = "Road Cobble Straight_3_6",
  Road_Cobble_Straight_3_7 = "Road Cobble Straight_3_7",
  Shop = "Shop",
  Soil_2 = "Soil_2",
  Soil_3 = "Soil_3",
  Soil_4 = "Soil_4",
  Soil_5 = "Soil_5",
  Soil_5_10 = "Soil_5_10",
  Soil_5_6 = "Soil_5_6",
  Soil_5_7 = "Soil_5_7",
  Soil_5_7_10 = "Soil_5_7_10",
  Soil_5_7_11 = "Soil_5_7_11",
  Soil_5_7_12 = "Soil_5_7_12",
  Soil_5_7_8 = "Soil_5_7_8",
  Soil_5_7_9 = "Soil_5_7_9",
  Soil_5_8 = "Soil_5_8",
  Soil_5_9 = "Soil_5_9",
  Soil_6 = "Soil_6",
  Stone_Brick_Wall_2 = "Stone Brick Wall_2",
  Stone_Brick_Wall_2_3 = "Stone Brick Wall_2_3",
  Stone_Brick_Wall_2_3_4 = "Stone Brick Wall_2_3_4",
  Stone_Brick_Wall_2_3_5 = "Stone Brick Wall_2_3_5",
  Stone_Brick_Wall_2_4 = "Stone Brick Wall_2_4",
  Stone_Brick_Wall_2_4_5 = "Stone Brick Wall_2_4_5",
  Stone_Brick_Wall_2_4_6 = "Stone Brick Wall_2_4_6",
  Stone_Brick_Wall_2_4_7 = "Stone Brick Wall_2_4_7",
  Stone_Brick_Wall_2_5 = "Stone Brick Wall_2_5",
  Stone_Brick_Wall_3 = "Stone Brick Wall_3",
  Stone_Brick_Wall_3_4 = "Stone Brick Wall_3_4",
  Stone_Brick_Wall_4 = "Stone Brick Wall_4",
  Stone_Brick_Wall_4_5 = "Stone Brick Wall_4_5",
  Stone_Brick_Wall_4_6 = "Stone Brick Wall_4_6",
  Street_Light = "Street Light",
  Text = "Text",
  Tile_1 = "Tile 1",
  dum_fire_0507090919_texture_glb = "dum_fire_0507090919_texture.glb",
  gravestone_glb = "gravestone.glb",
  praying_pot_glb = "praying pot.glb",
  scene_gltf = "scene.gltf",
  scene_gltf_2 = "scene.gltf_2",
} 
